backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  # 동행이야기
  - name: "stories"
    label: "동행이야기"
    folder: "src/content/stories"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: "title", label: "제목", widget: "string" }
      - { name: "date",  label: "작성일", widget: "datetime" }
      - { name: "thumbnail", label: "대표 이미지", widget: "image", required: false }
      - { name: "body", label: "본문", widget: "markdown" }

  # 공지/공모
  - name: "notices"
    label: "공지/공모"
    folder: "src/content/notices"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: "title", label: "제목", widget: "string" }
      - { name: "date",  label: "작성일", widget: "datetime" }
      - { name: "thumbnail", label: "대표 이미지", widget: "image", required: false }
      - { name: "body", label: "본문", widget: "markdown" }