backend:
  name: git-gateway
  branch: main

publish_mode: simple

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "stories"
    label: "동행이야기"
    folder: "src/content/stories"
    create: true
    format: "frontmatter"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "제목", name: "title", widget: "string" }
      - { label: "작성일", name: "date", widget: "datetime", format: "YYYY-MM-DDTHH:mm:ssZ" }
      - { label: "대표 이미지(선택)", name: "thumbnail", widget: "image", choose_url: true, required: false }
      - label: "카테고리"
        name: "category"
        widget: "select"
        options: ["인터뷰", "행사", "공탁", "공조동방"]
        default: "인터뷰"
      - { label: "본문", name: "body", widget: "markdown" }

  - name: "notices"
    label: "공지/공모"
    folder: "src/content/notices"
    create: true
    format: "frontmatter"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "제목", name: "title", widget: "string" }
      - { label: "작성일", name: "date", widget: "datetime", format: "YYYY-MM-DDTHH:mm:ssZ" }
      - { label: "대표 이미지(선택)", name: "thumbnail", widget: "image", choose_url: true, required: false }
      - label: "카테고리"              # ✅ 추가
        name: "category"
        widget: "select"
        options: ["공지", "공모"]
        default: "공지"
      - { label: "본문", name: "body", widget: "markdown" }

  - name: "faq"
    label: "faq"
    folder: "src/content/faq"
    create: true
    format: "frontmatter"
    slug: "{{slug}}"
    fields:
      - { label: "질문", name: "title", widget: "string" }
      - label: "카테고리"
        name: "category"
        widget: "select"
        options: ["후원관련 문의", "기부금영수증", "기타"]
        default: "후원관련 문의"
      - { label: "정렬 순서", name: "order", widget: "number", default: 0 }
      - { label: "노출 여부", name: "published", widget: "boolean", default: true }
      - { label: "답변", name: "body", widget: "markdown" }